### ISSUE TITLE
Switch to go template

### ISSUE THREAD

**Issue by alexellis** [mlabouardy/memes-faas#1]
Hi, you shouldn't need a Dockerfile for this.

Please see this guide - https://blog.alexellis.io/serverless-golang-with-openfaas/

and change "lang: Dockerfile" to "lang: go" in your YAML file.

**Comment by mlabouardy** [comment]
done

**Comment by alexellis** [comment]
Sorry it's still wrong. Please can you look at how the handler works in the blog post I shared with you or for example do faas-cli new --lang go example

**Comment by mlabouardy** [comment]
I followed the [example](https://github.com/mlabouardy/faas/blob/master/sample-functions/samples.yml), and it worked fine for me
